//
// Created by changzhi on 2026/2/15.
//

#ifndef MUSICPLAY_SORTTYPE_H
#define MUSICPLAY_SORTTYPE_H

enum SORT_TYPE {
    SORT_TITTLE_ASC, SORT_TITTLE_DESC,
    SORT_ARTIST_ASC, SORT_ARTIST_DESC,
    SORT_ALBUM_ASC, SORT_ALBUM_DESC,
    SORT_DURATION_ASC, SORT_DURATION_DESC,
    SORT_LAST_EDIT_TIME_ASC, SORT_LAST_EDIT_TIME_DESC,
    SORT_LEVEL_ASC, SORT_LEVEL_DESC,
    SORT_PLAY_NUMBER_ASC, SORT_PLAY_NUMBER_DESC
};

#endif //MUSICPLAY_SORTTYPE_H
